---
# tasks file for apache
- name: install apache
  apt: name=apache2 state=present update-cache=yes

- name: copy index.html
  template: 
    src: index.html.j2 
    dest: /var/www/html/index.html

- name: copy httpd conf
  template: 
    src: httpd.conf.j2 
    dest: /etc/apache2
  notify: restart apache

- name: start apache
  service: 
    name: apache2 state=started enabled=yes
