all:
  hosts:
    webserver1:
      ansible_host: 192.168.11.20
      server_name: webserver1
      document_root: /var/www/html
      enable_ssl: true
    webserver2:
      ansible_host: 192.168.11.30
      server_name: webserver2
      document_root: /var/www/html
      enable_ssl: false
    webserver3:
      ansible_host: 192.168.11.40
      server_name: webserver3
      document_root: /var/www/html
      enable_ssl: true