---
- hosts: database
  become: true
  tasks:
    - name: create demo database
      mysql_db: name=demo state=absent

    - name: create demo user
      mysql_user: name=demo password=demo priv=demo.*:ALL host='%' state=absent
