#SPDX-License-Identifier: MIT-0
---
# tasks file for nginx
#Vamos a parar Nginx si está corriendo
- name: Comprueba el estado de Nginx
  ansible.builtin.service_facts: #Recopila información sobre los servicios
- name: Detener Nginx si está activo
  ansible.builtin.service:
    name: nginx
    state: stopped
  when: ansible_facts.services['nginx.service'].state == 'running'
  #Condición para versiones antinguas para detener Nginx solo si está corriendo
  #when: ansible_facts.services['nginx'].state == 'running' 
