- name: Manejo de errores en Ansible
  hosts: all
  become: yes
  tasks:
    - name: Bloque principal
      block:
        - name: Tarea que puede fallar
          command: /bin/false
      rescue:
        - name: Manejo de error
          debug:
            msg: "La tarea falló, pero hemos manejado el error."
      always:
        - name: Tarea que siempre se ejecuta
          debug:
            msg: "Esta tarea siempre se ejecuta, independientemente del resultado del bloque."