- name: Passlib
  hosts: all
  become: yes
  tasks:
    - name: Install Python3
      apt:
        pkg:
          - python3
          - python3-pip
          - python3-passlib
      become: true

    - name: Create a symbolic link from python3 to python
      file:
        src: /usr/bin/python3
        dest: /usr/bin/python
        state: link

    - name: Set ansible_python_interpreter to use the installed Python
      set_fact:
        ansible_python_interpreter: /usr/bin/python3