- name: Reiniciar Nginx
  hosts: all
  become: yes
  tasks:
    - name: Reiniciar el servicio Nginx
      service:
        name: nginx
        state: restarted

    - name: Verificar el estado del servicio Nginx
      service_facts:

    - name: Mostrar estado del servicio Nginx
      debug:
        msg: "El servicio Nginx está {{ ansible_facts.services['nginx.service'].state }}"