- name: Crear usuarios con contrase単a en todos los servidores
  hosts: all
  become: yes
  vars:
    user_list:
      - user1
      - user2
      - user3
    user_password: "password" # Contrase単a en texto plano
  tasks:
    - name: Generar hash de la contrase単a en el controlador (local)
      ansible.builtin.set_fact:
        hashed_password: "{{ user_password | password_hash('sha512') }}"

    - name: Crear usuarios con contrase単a
      ansible.builtin.user:
        name: "{{ item }}"
        password: "{{ hashed_password }}"
        state: present
      loop: "{{ user_list }}"