---
- hosts: all
- name: Instalar webserver
  hosts: webserver
  become: yes
  gather_facts: yes
  roles:
    - role: apache2
    - role: php
    - role: pagina

- name: Instalar database 
  hosts: database
  become: yes
  gather_facts: yes
  roles:
    - role: mariadb
    
- name: Instalar loadbalancer 
  hosts: loadbalancer
  become: yes
  gather_facts: yes
  roles:
    - role: nginx
    - role: users